spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ayi_tp2
    username: joel
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
